env:
  global:
    - secure: "OfNoaAjDxWrQ4jsKOOCT14GdvfblTOG2Q8ufrw00WRk8KU9M5lX8ppa3HYZqSrPesgmNWF/2vOqdIEc/w/3jghNyWGaZwxgDflk+Dddpv50msq5a1lfiI4lAkvZoPIijYgRbCz+vucQmEhKkcto8eRAQRvF/WhWlzzzyzDNet+0v0U7bwLoj2ayBDcRCKTRwOsdlWCx3o4bhX9C6+Z+1LUbRZicIzBwzCnRPQ/jIKpBE0p/z5CVaLmSW/PcFgcHE4zKHuAEpShzaXLBldkm7M7dRdkP3xcbT+gD0ZO2A4eALaazWVrgRbziV/J+Rk1yrj4PkZ2mJgO2ecnXns0MCQxNJZplqIHRz+kptOBMcTtHaIxCrCbTPquibK2h/T1rHBZOTIXyZuJo4QfHnyrJ6QZaeh3w3h+IGbPA1Z5ykS/6rqGanBKYOB624j6SdK+JWouR50QnSN+x3n1d+W01x8t4/joh1q9aefBeVQ6tibscbVXJ3bO8q8VICR+J387A+ZFKYU2gc7195BQ93/6PSFjq7JIHzAvyuD3PYg5xf+LrqWBurRTMk+oAHflstaqHyE1vzZIO7owoNRWEt2OF+tmD3nFzOjA4uWiy3cjL3VKE3nHWJxQOPyB+Tpp1ADAZqkRWPzBZrbhEXiXGH6vPNcs5NZCQuoHr7uBdeb9iKV9Y="
    - # ^^ POSTMARK_API_TOKEN=?
    - secure: "V17wfqVlzmjRZ7UlA/LnSpYJTObBmozSw1xT+tu70+FCF3qPfE2zx27Vfp4jYIi7i0wNmW2DtTII9/skACyZMDERfnst3NSzAK6b4UZnh/1UdeKvMwdzPNFOL+lMHhG6G1DrlIjeswjhpcxgvGgRdpYl+Uj+a4I1EyfgSbduSqULl7kJLfkZADzszwIKfTd7OH4/ZNPzWirCj1gr9CWSnP3g8BqgqpuedkFqnI/7+a4uY6N6rWtJT/CF2syeS0sHGkqeMEG2JCKRp63jBeEWk3ED09DLwqOP+ZQZyhEC5WwXj8RF4pPSqOyrIHNWsoQMQ8cpa9+25Vz2sKubGq0E4gP8Eairf7U9ur6hs1ChNXNkLCqwm+amHgxp+xrSWeqeNA9wQb/H10OTLKvtMxEKQH0pH+l6eA5YLbsanx9FwZC++iQBxmSZfObd691aFRqIRTjy8sNMcn87X60V5j5z0JXh1ufPeQq0cWmu3aupOj+1MWMY56W883Ll6qnt+0eQJAxJCcoSvog1Cn28EG1222jcW+HPEB3S62CbaOBAe5Q5e27H3X78c2YszLiB0c8p1ytjSTrMtEWCiQ6ErszfhFBMmYkFqEXo1pfhcufcJe5gvSDtT1ej3a/mp+HMblssxxUyiNgqgvazqPNXNLdLwF5N0IDrT6zlD+RuGkSDkDk="
    - # ^^ POSTMARK_ACCOUNT_TOKEN=?
language: java
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
