version: 2.1

workflows:
  tests:
    jobs:
      - unit-tests:
          name: java21
          image: "cimg/openjdk"
          version: "21.0"
      - unit-tests:
          name: java22
          image: "cimg/openjdk"
          version: "22.0"
      - unit-tests:
          name: java23
          image: "cimg/openjdk"
          version: "23.0"
      - unit-tests:
          name: java24
          image: "cimg/openjdk"
          version: "24.0"
      - unit-tests:
          name: java25
          image: "cimg/openjdk"
          version: "25.0"
      - security-scan:
          context:
            - snyk

jobs:
  security-scan:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
      - run:
          name: Install Snyk CLI
          command: |
            curl -Lo ./snyk "https://static.snyk.io/cli/latest/snyk-linux"
            chmod +x ./snyk
            sudo mv ./snyk /usr/local/bin/
      - run:
          name: Run Snyk Scan
          command: |
            snyk auth $SNYK_TOKEN
            snyk monitor \
              --all-projects \
              --exclude=test \
              --org=$SNYK_ORG_ID

  unit-tests:
    parameters:
      version:
        type: string
      image:
        type: string
    docker:
      - image: << parameters.image >>:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: Versions
          command: |
            echo "java: $(java -version)"
      - run:
          name: Install dependencies
          command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
      - run:
          name: Run tests
          command: mvn test -DforkCount=1 -DreuseForks=false
