version: 2.1

workflows:
  tests:
    jobs:
      - unit-tests:
          name: java8
          image: "circleci/openjdk"
          version: "8"
      - unit-tests:
          name: java9
          image: "circleci/openjdk"
          version: "9"
          requires:
            - java8
      - unit-tests:
          name: java10
          image: "circleci/openjdk"
          version: "10"
          requires:
            - java9
      - unit-tests:
          name: java11
          image: "circleci/openjdk"
          version: "11"
          requires:
            - java10
      - unit-tests:
          name: java12
          image: "cimg/openjdk"
          version: "12.0.2"
          requires:
            - java11
      - unit-tests:
          name: java13
          image: "cimg/openjdk"
          version: "13.0.0"
          requires:
            - java12
jobs:
  unit-tests:
    parameters:
      version:
        type: string
      image:
        type: string
    docker:
      - image: << parameters.image >>:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: Versions
          command: |
            echo "java: $(java -version)"
      - run:
          name: Install dependencies
          command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
      - run:
          name: Run tests
          command: mvn test
