version: 2.1

workflows:
  java-tests:
    jobs:
      - unit-tests:
          name: java8
          version: "8"
      - unit-tests:
          name: java9
          version: "9"
          requires:
            - java8
      - unit-tests:
          name: java10
          version: "10"
          requires:
            - java9
      - unit-tests:
          name: java11
          version: "11"
          requires:
            - java10
      - unit-tests:
          name: java12
          version: "12.0.2"
          requires:
            - java11
      - unit-tests:
          name: java18
          version: "18.0.2"
          requires:
            - java12
      - unit-tests:
          name: java19
          version: "19.0.1"
          requires:
            - java18

jobs:
  unit-tests:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/openjdk:<< parameters.version >>
    steps:
      - checkout
      - run:
          name: Versions
          command: |
            echo "java: $(java -version)"
      - run:
          name: Install dependencies
          command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
      - run:
          name: Run tests
          command: mvn test
